spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ztzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
server:
  port: 8501
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
#自定义配置属性
ztzx:
  manager:
    noAuthUrls:
      - /admin/system/index/login
      - /v3/**
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
  minio:
    endpointUrl: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: yjs2312

